[!]
-- WebDNA fcgi admin include site head01 --
-- Version 8.0.0 --
-- 2021-12-30 --
[/!]
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=0.7, shrink-to-fit=yes">
<link rel="stylesheet" href="[showif [PAGEID]=welcome]Admin/[/showif]assets/css/admin.min.css">
<link rel="stylesheet" href="[showif [PAGEID]=welcome]Admin/[/showif]assets/css/all.min.css">
<link rel="stylesheet" href="[showif [PAGEID]=welcome]Admin/[/showif]assets/css/custom.css">
<link rel="icon" href="[showif [PAGEID]=welcome]Admin/[/showif]assets/favicon/favicon-32x32.png" type="image/x-icon" />