[!]
-- WebDNA fcgi admin include site scripts01 --
-- Version 8.0.0 --
-- 2021-12-30 --
[/!]
<script src="[showif [PAGEID]=welcome]Admin/[/showif]assets/js/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="[showif [PAGEID]=welcome]Admin/[/showif]assets/js/bootstrap-4-3-1.min.js"></script>
<script src="[showif [PAGEID]=welcome]Admin/[/showif]assets/js/admin.js"></script>